In [124]:
import pandas as pd

df = pd.read_csv('csv/books.csv',on_bad_lines='skip',encoding='latin-1',sep=';')
df.head()

C:\Users\PURVESH\AppData\Local\Temp\ipykernel_15476\2063755278.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('csv/books.csv',on_bad_lines='skip',encoding='latin-1',sep=';')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [126]:
# No of duplicate records with same title 

# len(df) - len(df['Book-Title'].unique())


df.duplicated(subset='Book-Title').sum()

29225

In [127]:
df1 = df.drop_duplicates(subset='Book-Title')

print(len(df1))

242135

In [128]:
df1.duplicated(subset='Book-Title').sum()

0

In [129]:
sample_size = 8000
df8k = df1.sample(n=sample_size, replace=False, random_state=490)

df8k = df8k.reset_index()
df8k = df8k.drop('index',axis=1)

In [130]:
df8k.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0060972491,"Thank You, Jeeves",P.G. Wodehouse,1989,Perennial,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...
1,015602781X,Pincher Martin: The Two Deaths of Christopher ...,William Golding,2002,Harvest Books,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...
2,1561441627,The Nutcracker (Christmas Fun-to-Read Fairy Ta...,Roberta Collier-Morales,1992,Modern Publishing,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...
3,1402708610,I Know a Rhino,Charles Fuge,2003,Sterling,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...
4,0441586325,Norby and the Oldest Dragon,Janet Asimov,1993,Ace Books,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...

In [131]:
df8k[['Book-Title', 'Book-Author', 'Publisher']]

,Book-Title,Book-Author,Publisher
0,"Thank You, Jeeves",P.G. Wodehouse,Perennial
1,Pincher Martin: The Two Deaths of Christopher ...,William Golding,Harvest Books
2,The Nutcracker (Christmas Fun-to-Read Fairy Ta...,Roberta Collier-Morales,Modern Publishing
3,I Know a Rhino,Charles Fuge,Sterling
4,Norby and the Oldest Dragon,Janet Asimov,Ace Books
...,...,...,...
7995,Algebra (Teach Yourself),P. Abbott,McGraw-Hill
7996,Sweepers: A Novel of Suspense,Peter T. Deutermann,St. Martin's Press
7997,"Prince of Kisses (Faerie Tale Romance Series ,...",Colleen Shannon,Love Spell
7998,I'm a Little Teapot,Iza Trapani,Charlesbridge Publishing
7999,Klar Schiff zum Gefecht. Richard Bolitho - Kap...,Alexander Kent,Ullstein Buchverlage GmbH &amp; Co. KG / Ullst...

In [132]:
def clean_text(text):
    result = str(text).lower()
    return result.replace(" ", "")

In [133]:
# df1[['Book-Title', 'Book-Author', 'Publisher']].head()

df8k['Book-Author'] = df8k['Book-Author'].apply(clean_text)

df8k[['Book-Title', 'Book-Author', 'Publisher']].head()

,Book-Title,Book-Author,Publisher
0,"Thank You, Jeeves",p.g.wodehouse,Perennial
1,Pincher Martin: The Two Deaths of Christopher ...,williamgolding,Harvest Books
2,The Nutcracker (Christmas Fun-to-Read Fairy Ta...,robertacollier-morales,Modern Publishing
3,I Know a Rhino,charlesfuge,Sterling
4,Norby and the Oldest Dragon,janetasimov,Ace Books

In [134]:
df8k['Book-Title'] = df8k['Book-Title'].str.lower()
df8k['Publisher'] = df8k['Publisher'].str.lower()

In [135]:
df8k[['Book-Title', 'Book-Author', 'Publisher']]

,Book-Title,Book-Author,Publisher
0,"thank you, jeeves",p.g.wodehouse,perennial
1,pincher martin: the two deaths of christopher ...,williamgolding,harvest books
2,the nutcracker (christmas fun-to-read fairy ta...,robertacollier-morales,modern publishing
3,i know a rhino,charlesfuge,sterling
4,norby and the oldest dragon,janetasimov,ace books
...,...,...,...
7995,algebra (teach yourself),p.abbott,mcgraw-hill
7996,sweepers: a novel of suspense,petert.deutermann,st. martin's press
7997,"prince of kisses (faerie tale romance series ,...",colleenshannon,love spell
7998,i'm a little teapot,izatrapani,charlesbridge publishing
7999,klar schiff zum gefecht. richard bolitho - kap...,alexanderkent,ullstein buchverlage gmbh &amp; co. kg / ullst...

In [136]:
df8k

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0060972491,"thank you, jeeves",p.g.wodehouse,1989,perennial,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...,http://images.amazon.com/images/P/0060972491.0...
1,015602781X,pincher martin: the two deaths of christopher ...,williamgolding,2002,harvest books,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...,http://images.amazon.com/images/P/015602781X.0...
2,1561441627,the nutcracker (christmas fun-to-read fairy ta...,robertacollier-morales,1992,modern publishing,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...,http://images.amazon.com/images/P/1561441627.0...
3,1402708610,i know a rhino,charlesfuge,2003,sterling,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...,http://images.amazon.com/images/P/1402708610.0...
4,0441586325,norby and the oldest dragon,janetasimov,1993,ace books,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...,http://images.amazon.com/images/P/0441586325.0...
...,...,...,...,...,...,...,...,...
7995,0844239046,algebra (teach yourself),p.abbott,1992,mcgraw-hill,http://images.amazon.com/images/P/0844239046.0...,http://images.amazon.com/images/P/0844239046.0...,http://images.amazon.com/images/P/0844239046.0...
7996,0312156693,sweepers: a novel of suspense,petert.deutermann,1997,st. martin's press,http://images.amazon.com/images/P/0312156693.0...,http://images.amazon.com/images/P/0312156693.0...,http://images.amazon.com/images/P/0312156693.0...
7997,0505522004,"prince of kisses (faerie tale romance series ,...",colleenshannon,1997,love spell,http://images.amazon.com/images/P/0505522004.0...,http://images.amazon.com/images/P/0505522004.0...,http://images.amazon.com/images/P/0505522004.0...
7998,1580890105,i'm a little teapot,izatrapani,1998,charlesbridge publishing,http://images.amazon.com/images/P/1580890105.0...,http://images.amazon.com/images/P/1580890105.0...,http://images.amazon.com/images/P/1580890105.0...
7999,3548239323,klar schiff zum gefecht. richard bolitho - kap...,alexanderkent,1996,ullstein buchverlage gmbh &amp; co. kg / ullst...,http://images.amazon.com/images/P/3548239323.0...,http://images.amazon.com/images/P/3548239323.0...,http://images.amazon.com/images/P/3548239323.0...

In [137]:
_df2 = df8k.drop(['ISBN','Image-URL-S','Image-URL-M','Image-URL-L','Year-Of-Publication'],axis=1)

_df2

,Book-Title,Book-Author,Publisher
0,"thank you, jeeves",p.g.wodehouse,perennial
1,pincher martin: the two deaths of christopher ...,williamgolding,harvest books
2,the nutcracker (christmas fun-to-read fairy ta...,robertacollier-morales,modern publishing
3,i know a rhino,charlesfuge,sterling
4,norby and the oldest dragon,janetasimov,ace books
...,...,...,...
7995,algebra (teach yourself),p.abbott,mcgraw-hill
7996,sweepers: a novel of suspense,petert.deutermann,st. martin's press
7997,"prince of kisses (faerie tale romance series ,...",colleenshannon,love spell
7998,i'm a little teapot,izatrapani,charlesbridge publishing
7999,klar schiff zum gefecht. richard bolitho - kap...,alexanderkent,ullstein buchverlage gmbh &amp; co. kg / ullst...

In [138]:
df2 = _df2
df2['data'] = df2['Book-Title'].astype('str')+ ' ' + df2['Book-Author'].astype('str') + ' ' + df2['Publisher'].astype('str')

print(df2['data'])

0               thank you, jeeves p.g.wodehouse perennial
1       pincher martin: the two deaths of christopher ...
2       the nutcracker (christmas fun-to-read fairy ta...
3                     i know a rhino charlesfuge sterling
4       norby and the oldest dragon janetasimov ace books
                              ...
7995        algebra (teach yourself) p.abbott mcgraw-hill
7996    sweepers: a novel of suspense petert.deuterman...
7997    prince of kisses (faerie tale romance series ,...
7998    i'm a little teapot izatrapani charlesbridge p...
7999    klar schiff zum gefecht. richard bolitho - kap...
Name: data, Length: 8000, dtype: object

In [139]:
from sklearn.feature_extraction.text import CountVectorizer

#test = pd.DataFrame({'data': ['Hello Beautiful Word', 'Hello There']})

vectorizer = CountVectorizer()
vectorized = vectorizer.fit_transform(df2['data'])

In [140]:
# xx = {'a': ['hello', 'there'], 'b': [1, None]}

# test = pd.DataFrame(xx)


# test.dropna()
print(vectorizer.get_feature_names_out())
# print(vectorized)
print(vectorized.toarray())
print(vectorized.shape)

['00' '000' '003' ... 'â¼ter' 'â¼tz' 'â¼tzt']

MemoryError: Unable to allocate 1.19 GiB for an array with shape (8000, 20033) and data type int64

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(vectorized)

print(similarities)
print(similarities.shape)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.07692308 ... 0.0836242  0.         0.        ]
 [0.         0.07692308 1.         ... 0.         0.12403473 0.        ]
 ...
 [0.         0.0836242  0.         ... 1.         0.         0.        ]
 [0.         0.         0.12403473 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
(8000, 8000)

In [ ]:
# Remapping the simailarties vector back to the previos dataframe

df2 = pd.DataFrame(similarities , columns=df8k['Book-Title'], index=df8k['Book-Title']).reset_index()
df2['Year-Of-Publication'] = df1['Year-Of-Publication']
df2['Image-URL-M'] = df1['Image-URL-M']
df2.head()

Book-Title,Book-Title,"thank you, jeeves",pincher martin: the two deaths of christopher martin,the nutcracker (christmas fun-to-read fairy tales ser),i know a rhino,norby and the oldest dragon,his eminence and hizzoner,el oro de los sueã±os (leer en espaã±ol nivel 4),celestine insights,feng shui and money: a nine-week program for creating wealth using ancient principles and techniques,...,"the four witnesses : the rebel, the rabbi, the chronicler, and the mystic -- why the gospels present strikingly different visions of jesus?",html prorammer's reference,the executed god: the way of the cross in lockdown america,algebra (teach yourself),sweepers: a novel of suspense,"prince of kisses (faerie tale romance series , no 2)",i'm a little teapot,klar schiff zum gefecht. richard bolitho - kapitã?â¤n des kã?â¶nigs.,Year-Of-Publication,Image-URL-M
0,"thank you, jeeves",1.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.0,2002,http://images.amazon.com/images/P/0195153448.0...
1,pincher martin: the two deaths of christopher ...,0.0,1.000000,0.076923,0.0,0.196116,0.098058,0.000000,0.113228,0.000000,...,0.264198,0.0,0.236525,0.0,0.27735,0.083624,0.000000,0.0,2001,http://images.amazon.com/images/P/0002005018.0...
2,the nutcracker (christmas fun-to-read fairy ta...,0.0,0.076923,1.000000,0.0,0.098058,0.000000,0.069338,0.000000,0.000000,...,0.226455,0.0,0.177394,0.0,0.00000,0.000000,0.124035,0.0,1991,http://images.amazon.com/images/P/0060973129.0...
3,i know a rhino,0.0,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.0,1999,http://images.amazon.com/images/P/0374157065.0...
4,norby and the oldest dragon,0.0,0.196116,0.098058,0.0,1.000000,0.250000,0.000000,0.144338,0.158114,...,0.336788,0.0,0.226134,0.0,0.00000,0.000000,0.000000,0.0,1999,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
input_book = 'norby and the oldest dragon'
recommendations = pd.DataFrame(df2.nlargest(11,input_book)[['Book-Title', 'Year-Of-Publication', 'Image-URL-M']])
recommendations = recommendations[recommendations['Book-Title']!=input_book]
recommendations

Book-Title,Book-Title,Year-Of-Publication,Image-URL-M
881,dragon's domain,2001,http://images.amazon.com/images/P/0743211383.0...
7302,the windsingers,1998,http://images.amazon.com/images/P/1853260770.0...
923,the guardians (ace fantasy),1987,http://images.amazon.com/images/P/0345346971.0...
1235,the dragon and the unicorn,1974,http://images.amazon.com/images/P/3518367064.0...
3850,the city and the pillar,1997,http://images.amazon.com/images/P/3423123222.0...
4855,the best and the brightest,1998,http://images.amazon.com/images/P/0385333498.0...
5719,ou lu khen and the beautiful madwoman,2002,http://images.amazon.com/images/P/8472234320.0...
5980,the quark and the jaguar: adventures in the si...,NaN,NaN
2138,the black castle,1998,http://images.amazon.com/images/P/0373301529.0...
2740,jed the dead,2002,http://images.amazon.com/images/P/0380811065.0...

In [ ]:
# import json
# recommendations.to_numpy().tolist()
# recommendations.to_json(orient='records')

In [ ]:
# import json

# df8k[df8k['Book-Title'].str.contains("golden")][:3].to_json(orient='records')